### ISSUE TITLE
Task: Move the logic for detecting the assign logic into the action itself so a user can just include the step

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT-Action#10]
![image](https://github.com/OWASP/BLT-Action/assets/128622481/3a93e91f-1aec-4064-8c23-3776447df45f)

**Comment by JisanAR03** [comment]
@DonnieBLT  sir, the updated yml file will look like 
![image](https://github.com/OWASP/BLT-Action/assets/97744811/a288a985-bbf8-48c1-9dd4-c242a62b205e)

Now I need keywords for:
const assignKeywords = ['/assign', 'assign to me', 'assign this to me', 'please assign me this', 'i can try fixing this', 'i am interested in doing this', 'i am interested in contributing'];

const unassignKeywords = ['/unassign'];

for now, I tested my updated code using this keyword. Now I need confirmation for which keyword we should use at those variables.

**Comment by DonnieBLT** [comment]
You can get the keyword from the screenshot or the action that is running on the BLT repo

**Comment by JisanAR03** [comment]
@DonnieBLT  sir , we can close this issue
