### ISSUE TITLE
Default the repository value?

### ISSUE THREAD

**Issue by kingthorin** [OWASP/BLT-Action#15]
Won't this almost always be the necessary value?
```yml
repository: ${{ github.repository }}
```

Why not simply default it and allow users to override instead of requiring it to be set as a `with` value?

**Comment by DonnieBLT** [comment]
Good call!  Thanks. @JisanAR03 can you make that change please?

**Comment by JisanAR03** [comment]
@DonnieBLT  sir , we can close this issue

**Comment by kingthorin** [comment]
For future reference you can close issues from pull requests on merge using key words: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue

**Comment by JisanAR03** [comment]
> @JisanAR03 For future reference you can close issues from pull requests on merge using keywords: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue

@kingthorin  sir , Thanks for the docs sir, I will something about it for sure☺

**Comment by JisanAR03** [comment]
@DonnieBLT sir , to close an issue automatically, as @kingthorin sir says, I come with a solution.

-  We can do "if (eventType == "pull_request")" in the existing index.js file, and based on the condition, if the user mentions the issue number like "fix_issue_#10," the issue will close automatically when the PR has approval for the merge.


It's just an approach, sir. Any suggestions for me to implement auto-issue close action?

**Comment by kingthorin** [comment]
Oh I was just pointing it for the next time you worked on an issue so that you did t have to ask someone to close things.

I didn't mean for it to be something you had to integrate. (If you can and want to then cool, but that wasn't the point 🙂)

**Comment by DonnieBLT** [comment]
Also, if you use GitHub to create the branch from the issue, it will automatically link it to the information section on the right.

**Comment by JisanAR03** [comment]
@kingthorin , sorry for my misunderstanding, sir😬
@DonnieBLT ok sir sure😊

**Comment by kingthorin** [comment]
No worries. Looking back I wasn't very clear.

**Comment by kingthorin** [comment]
For my 2 cents this issue has been addressed, I'm happy to close it if you want. Just let me know @JisanAR03

**Comment by JisanAR03** [comment]
> For my 2 cents this issue has been addressed, I'm happy to close it if you want. Just let me know @JisanAR03

@kingthorin yes sir sure
