### ISSUE TITLE
Task: Fix the auto assign GitHub action, so that if the other issue has a pull request attached, it allows for further assignment of multiple issues as long as each issue has a pull request

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT-Action#7]

**Comment by DonnieBLT** [comment]
The code is here https://github.com/OWASP/BLT-Action/blob/main/src/index.js

**Comment by JisanAR03** [comment]
> The code is here https://github.com/OWASP/BLT-Action/blob/main/src/index.js

@DonnieBLT  thank you sir, it's very much clear now☺

**Comment by JisanAR03** [comment]
now this issue is closed by #12
